### ISSUE TITLE
请问您这个项目的开源许可证是什么？

### ISSUE THREAD

**Issue by Feiox** [eisneim/gortfolio#1]
可以将您项目中部分 react 代码用于不公开的商业项目吗？

**Comment by eisneim** [comment]
MIT 随便你怎么用，目前比较忙还没有时间继续完善后台。

**Comment by Feiox** [comment]
THX 可以将您的名字添加到我们的感谢列表并连接到您的 GitHub 主页吗？

**Comment by eisneim** [comment]
@Feiox 可以
